### ISSUE TITLE
General MIDI Emulation - one of the links not working

### ISSUE THREAD

**Issue by Torinde** [rderooy/dosbox-x-wiki#4]
At https://dosbox-x.com/wiki/Guide%3ASetting-up-MIDI-in-DOSBox%E2%80%90X

Table of contents link is
- https://dosbox-x.com/wiki/Guide%3ASetting-up-MIDI-in-DOSBox%E2%80%90X#_general_midi_emulation
While link in the MT-32 section Sound Canvas box is
- https://dosbox-x.com/wiki/Guide%3ASetting-up-MIDI-in-DOSBox%E2%80%90X#General-MIDI-Emulation

The second one doesn't work.

I tried correcting that, but in the source it seems both are the same (except capital letters) ??
- https://github.com/rderooy/dosbox-x-wiki/blob/master/Guide:Setting-up-MIDI-in-DOSBox%E2%80%90X.asciidoc#general-midi-emulation
- https://github.com/rderooy/dosbox-x-wiki/blob/master/Guide:Setting-up-MIDI-in-DOSBox%E2%80%90X.asciidoc#General-MIDI-Emulation

**Comment by rderooy** [comment]
The TOC is automatically generated. You can see it in the source document as `:toc: macro`. So I suspect the issue is not with the source document, but rather with the html conversion, which I don't control.

In fact, if you click this link, you will see that it works:
https://github.com/joncampbell123/dosbox-x/wiki/Guide%3ASetting-up-MIDI-in-DOSBox%E2%80%90X#general-midi-emulation

As I don't control the html conversion, it is out of my hands, and I suggest you raise an issue on the dosbox-x issues.
